before_script:
- npm i --save @types/react-router-dom

language: node_js
node_js:
- node
notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: fZDTpfm4/91R5P85cF7hIowAcxU5n6QQiA/1t5sSNPIoTWaVNvwSJyRH+u+ZZA79i+7sixPzOMHhAVrloB7hBsvngp2P4J2TJ4F7FMT+qwcQ0P0L1tnopD4F219faw/vEbM6inG/lpB8uQ5pHYSApIOxbi2koO0ebsQ5JtlHWypQYUeOmnRVRSQ6CyK5mT5s7PyrdVDxZ1kQqAPRj31pHyV3qzppPLBwEhWPHv81Z3/KB0RZtQ5/Wr7QZdxFQsxQdWOJbEC8zL0GpXFnF3c4bsqs82+jpR0N6yhOVFWOl36ObDcMyGdOpPNH1XiGROv/WGaPhopbW4e2dhVmQFFp0scPUIdQHZz6u0HT/KhG/Z9oE2a0hF95hN+xSIXiCYEW8j8l+TCxns6IV2VSmWACsImv/+Jk7HXmb70nbmB3LiKbIMASbC0QV0D3V62HJmx2v7zh29iOppCPXYVzTRCpwS2yGpqqoZP2XQa6MTb2ImH79VQetEyicUaw9Ah7+pLtXC8Oj09ePYvnXdR+ittK6sGya7Y4n7Gbd+WBD2IZydkDBAC4TXWHjQLWnjSINO6MIyXhieR/LwohMHs6zV5Dm2H2i1oOfcN5pZ8p+hutdYgK/7DpGjGXhwnr1j8Kc+7lPoMbZ7DHbTHEDC1dCmPCxeMg4aH/kugwMgn8nIHIOiY=
  app: m-oodytunes
  skip_cleanup: true
