language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Xx1dBnH0EDLGQZdu3XISq6OD21Zn3uGExTWNHZka7XIgSUA6JzYt5P4+O3PFq8IKGvK/vu6vUaZxGbNrCoFjzzemjlk4bua6i+A51vVdViuAdoqXZKOidwwkH48wvdU4fJgNRP3kLzLBuCC5cXgU6cdW7xjWk5LZoevmptuUh+MtSfa3p4d3gl1vBEUVuHgWUtlcrn743gfHRILI9E5vRqmM/rs5EupK8yYm4fSlckQ+S4wJK2fJy3NDWJ8t4wqYB7G9+XKjuKzK//1PoroYnXyUaSwAzIXpGnetCbCt9HyQ4iUJvAUmmaa6anM6ti3RWQuNNNRfYNS5WylefwrKr0Qdq6VLeYQezGGYZIuN9XoKoHYLFaQx1OlpBHkRgoe1kjlWwhojT3C6F5zjZdZUBZwtrKOvIncVtbsKu5XocFJwznIuyHAkG7bOb2/XHVi0PJF8R1oTif/lElmPwzPNszuxobyNG/EH6AE2Ut9fgt1yQQkFZHSNNFaHdR8RZzHmHvE63bEvPk2DvYCHHfM+DEiZVzjrGVtUBtsp5xyzuYVIX69gd3A9xKx9NyEekUHqtR5sIxw+kRdTSduHotz6Q5tG+Bu96cWpESQaPLZvk7cRsFStOOoWjU/NSsHY+tUAMo/c7tJ6mwKTzNaNQ5mrBOkabrZDCHE71N3197zG/b4=
  app: moodytunes
  on: main
