before_script:
- npm i --save @types/react-router-dom

language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: OpAb3vfGFgcn0HlDhq9jrxKTcll+5+ukOZsxHiqNJMzGxLvFI7ioFongsZsCvhI2yJfq6MA22VSLpEA8NfS2/uAnOFp3ZsAsEV5556wDt5MA9IkLn6dwr6qLUzAjZ06/7JGEjf+zCzhalrBK6jyaP5ptq2jB6xXEdFAU8sCnVHfYKzswoXQEdn41KGycrNCfmRstJ0jiD4ziZfExKS76X8Kx2fbHIeHPWtI7zyAwQ6h0ELlBYdMkYuRRNSgBCFhT6Cgpoh+nJomFcy6K8whKSOIXr6B7KWtZrNp6OlCkeoBHPqmZJhVnD6FtcYZe5o3guHadZe3Qr5I7mk4tn+3kRyP3UrGyvQZ467DwjlKpYYa6PFcTsWmsXbskz2NaqXaqHiG5SgNX3NlP67ZvdalS3MW2C3Ndsg8tGSj1pK6wbGfm32WXwxU54qYth2oJxlB/JCjdbWLJVX8qZ0bIRdBFZ6d57LaSOUqfOGyTIPibZljjTQe1ak0z4snpgXE1mmmsrTg9lvtTs6CUnGHakd1C4vOs6eA5A+l10RH3XAHvdaxk1fitEUV3THu6aYhF510QiaUjowpHiV0iY5anseqf6OPI2c7xf6GWAhlkFAjhMVGxQ+q6fhBlNUeVrH3pRPmCQx/JWYYZqrK1B1621mK1HOre4HknMQ1NkQx/AvbD2qw=
  app: moodytunes
  skip_cleanup: true