language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: HOWHHwiU8iIYUmhJBV35CZyT8GM/JkB3xFOfkafefQRpbmheRO678Sy0cWFnLbpaUR3ZK4NCJYP6yrq6afyw442SzTcLHxeH1ALFfYIlFvD6FLlGSm5v41RqVcOmKZRH7o0UhEMv4rNZXaxtO6H/r0lLWYQbs47OGHtecFdXSoWOPdoLyZNTVmyO440lYpaxjsq4CsiHPFPhlm0hsq2+XjWcgBdcxjICTckqeomQSPzeDk7Bae77PZVvQIQY0saZpsGqeNrloHYmfN7Z/Uxm5UlirC2T4iBA25ZQiM1ns9zKP9CyDkJlcxPjWnkZ+Z7NQ58pIhHMiHWfyJPItKWRqy3at0obBifXz33/gX680zQ7wjf6mJXn63QABV2S4FBio/zYiadnodd84QzEtmI3Gz4Eero3DCxvX/rpsmJDJIWdh0RsxlxtL2MmCzkQesF3E5EG16BO/ms0Op4gz4i4qD4FLqCQEFe9V0By1qXm/SZaPvjhe9pwgi9ztSOW5DtpSOlGBfLMgF3HxSfhZhJYWv+fErZomEgIR8EJzjjGEAXz6tzSI7YYY+k55F7jrm4fTSKO044yEGRZ9L+RJBP48uy0vPfxKV+jnbggBDwa7OZK9iEnrCEusonY42ny58xkjfnK5P6H1TGr/gsAw15aragZ4rmH2kRxt6xNystG6ok=
  app: moodytunes
  on: main
