language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ROIU5sHpyK4BxntAV37Y2JNng4/HVhMLyRK5nyRPrVMXMqM+nRj8p+denxXrGS8qGtHo/rcLx8g3uYNY6dqOA++9P5+2HOBkthR1KeRtCx9yXZ4Fv+ph2wwc3eXiOluF1ZN9UZ+njkC5xL0goByoi7XtCmFLZG/+Q0TNOwZekEE35EaKVRoUAJi7k5GMJdVdt2oVdERIRQveAMonZY/CQgaDrMWpcqrQXPfMATocxM5UUS09D+R4wHW9P5rM3o8VH1DjBPcB3ixSOn7H8z0JHfP0TZ8N/hiNySnBR/PKlglmsn8Vn80QnR9EZWV9DpnZIoOieplCKJWcZNFnY7LJAkQ+sF+BEQMD3LfpcLiUow/NNG+/85jNavR2d7mj1KGr0JdbwLI+awW4V8yIFUsNOseT32UBDtVGNvpAHp6eHHqifYb0M+67dpVxQiMCCcJasg5wZIxz9k1tWAm4wXxkd3/J8mDSwpoMyHA6vYbmABRloNfa2qcVBPnbfIE1ph70oK7O2GHcCVR4jlj/Xt2LTPz/8hKTEnAFGdnbzCuKQVIzVt4ZzIBAbA/byOM2MCxyVc+FV/2y2qvwooO3KuoChji2YrUA2z+M60kIokDx10MLRTf89aRovPYa8LBi5DAOXqZ5XgT5BuCKUbTUKrinfsOjFvGrMoMWbQdjAYXbNDU=
  app: moodytunes
  on: main
