language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: GQ1WmU1/eu2wWK7tqqAwgsn+QCb8izWk85JyYU25Eauxfzv/r/Q4R7g4gAvN3chn3SioA6RdbzXHdNk/NY20nnoFruJRQGPDpLuV9qieJFBZjvqjQtpy9mraCviYF0vJZlrYkoOKXneR8GyFHTj4kkRXfynRq6OmqsxVWB4zxbNp1s0hfXUapI3dbsQLDcWCkzHCd75eUFQVdoGqWbhmPdBCVj1qHo66Z12x0KKoduRvCRH1FdMD5Qq0zLDENRixyxdr5rTl9bDIO1zpXkXPYod8bBW0cofd+3HQj90dac/H11LHmR8vXR/+56SG/jHpfM2r8VAyACgQmAcNwFYzEhJY67hgfjJDeB22vDqqn6fRjgnb/9Je0eJeBCPISs1KrV4jVlhfIBInRyJsv3QeniIX5t2Wj8urXbWHRlctSvyup+PJ2W0ec++o45mcijkgdrZta2v0EdocTOmzNtnvXFR0UIttCT8jGmLH4DR4kdqY9D0EEPTJ9it1dItqsHBzlMvSfUHcogDVOS677EpiEgM0C6nPPvw78oDpYX7AOS0I7bVYNsKpZuUbKCDXAjAxK4Q2BdSh/obqjJufbm/6wxpYA1ZHGLe0yFJE2CY0Mkko5n9jIgWCciRi/kGKTjnfoeeB4IqL1s4a5CvK9aXy4DcgwO6uIsp5yaKsZ8kP6Jw=
  app: moodytunes
  on: main
